// <auto-generated />
using System;
using Fluffy.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fluffy.Api.Migrations
{
    [DbContext(typeof(FluffyDbContext))]
    [Migration("20261008184654_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fluffy.Api.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.HasKey("Id");

                    b.HasIndex("OrderIndex");

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Chapter 1 introduces travel vocabulary, simple trip plans, and describing travel experiences.",
                            OrderIndex = 1,
                            Title = "Traveling"
                        });
                });

            modelBuilder.Entity("Fluffy.Api.Models.TestAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("TestAnswers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerText = "жұмыс",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            AnswerText = "демалыс",
                            IsCorrect = true,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 3,
                            AnswerText = "сабақ",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 4,
                            AnswerText = "саяхатшы",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 5,
                            AnswerText = "suitcase",
                            IsCorrect = true,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 6,
                            AnswerText = "station",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 7,
                            AnswerText = "passport",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 8,
                            AnswerText = "map",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 9,
                            AnswerText = "amazing",
                            IsCorrect = true,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 10,
                            AnswerText = "late",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 11,
                            AnswerText = "empty",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 12,
                            AnswerText = "usual",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 13,
                            AnswerText = "adventure vacation",
                            IsCorrect = true,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 14,
                            AnswerText = "quiet homework",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 15,
                            AnswerText = "daily routine",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 16,
                            AnswerText = "simple lunch",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 17,
                            AnswerText = "a trip plan",
                            IsCorrect = true,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 18,
                            AnswerText = "a heavy bag",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 19,
                            AnswerText = "a train ticket",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 20,
                            AnswerText = "a beach photo",
                            IsCorrect = false,
                            QuestionId = 5
                        });
                });

            modelBuilder.Entity("Fluffy.Api.Models.TestQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("TestQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            QuestionText = "What does \"vacation\" mean?",
                            QuestionType = "MultipleChoice",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            QuestionText = "Choose the correct word: I packed my clothes in a ____.",
                            QuestionType = "MultipleChoice",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            QuestionText = "Which word can describe a very good travel experience?",
                            QuestionType = "MultipleChoice",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            QuestionText = "Which vacation type is usually connected with excitement and new activities?",
                            QuestionType = "MultipleChoice",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            QuestionText = "What is an itinerary?",
                            QuestionType = "MultipleChoice",
                            TopicId = 4
                        });
                });

            modelBuilder.Entity("Fluffy.Api.Models.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ScopeLabel")
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserName");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("Fluffy.Api.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId", "OrderIndex");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChapterId = 1,
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Learn common vacation words and short travel sentences.",
                            IsActive = true,
                            OrderIndex = 1,
                            Title = "We're going on vacation"
                        },
                        new
                        {
                            Id = 2,
                            ChapterId = 1,
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Practice describing trips, places, and memories.",
                            IsActive = true,
                            OrderIndex = 2,
                            Title = "Description of travel experiences"
                        },
                        new
                        {
                            Id = 3,
                            ChapterId = 1,
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compare beach, city, adventure, and family vacations.",
                            IsActive = true,
                            OrderIndex = 3,
                            Title = "Discussing types of vacation"
                        },
                        new
                        {
                            Id = 4,
                            ChapterId = 1,
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Use practical phrases for booking, schedules, and packing.",
                            IsActive = true,
                            OrderIndex = 4,
                            Title = "Trip planning"
                        });
                });

            modelBuilder.Entity("Fluffy.Api.Models.Vocabulary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExampleSentence")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("PartOfSpeech")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Vocabulary");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "We are going on vacation next week.",
                            PartOfSpeech = "noun",
                            TopicId = 1,
                            Translation = "демалыс",
                            Word = "vacation"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "I bought a train ticket online.",
                            PartOfSpeech = "noun",
                            TopicId = 1,
                            Translation = "билет",
                            Word = "ticket"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "My suitcase is ready for the trip.",
                            PartOfSpeech = "noun",
                            TopicId = 1,
                            Translation = "чемодан",
                            Word = "suitcase"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "The mountain view was amazing.",
                            PartOfSpeech = "adjective",
                            TopicId = 2,
                            Translation = "керемет",
                            Word = "amazing"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "The station was crowded in the morning.",
                            PartOfSpeech = "adjective",
                            TopicId = 2,
                            Translation = "адам көп",
                            Word = "crowded"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "An adventure vacation can be exciting.",
                            PartOfSpeech = "noun",
                            TopicId = 3,
                            Translation = "шытырман оқиға",
                            Word = "adventure"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "A beach vacation is relaxing.",
                            PartOfSpeech = "adjective",
                            TopicId = 3,
                            Translation = "тынықтыратын",
                            Word = "relaxing"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "Our itinerary includes two museums.",
                            PartOfSpeech = "noun",
                            TopicId = 4,
                            Translation = "сапар жоспары",
                            Word = "itinerary"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "We made a hotel reservation.",
                            PartOfSpeech = "noun",
                            TopicId = 4,
                            Translation = "бронь",
                            Word = "reservation"
                        });
                });

            modelBuilder.Entity("Fluffy.Api.Models.TestAnswer", b =>
                {
                    b.HasOne("Fluffy.Api.Models.TestQuestion", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Fluffy.Api.Models.TestQuestion", b =>
                {
                    b.HasOne("Fluffy.Api.Models.Topic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Fluffy.Api.Models.TestResult", b =>
                {
                    b.HasOne("Fluffy.Api.Models.Topic", "Topic")
                        .WithMany("TestResults")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Fluffy.Api.Models.Topic", b =>
                {
                    b.HasOne("Fluffy.Api.Models.Chapter", "Chapter")
                        .WithMany("Topics")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Fluffy.Api.Models.Vocabulary", b =>
                {
                    b.HasOne("Fluffy.Api.Models.Topic", "Topic")
                        .WithMany("Vocabulary")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Fluffy.Api.Models.Chapter", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("Fluffy.Api.Models.TestQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Fluffy.Api.Models.Topic", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("TestResults");

                    b.Navigation("Vocabulary");
                });
#pragma warning restore 612, 618
        }
    }
}
